In [2]:
import pandas as pd
import numpy as np
df=pd.read_csv("football_data.csv")
df.drop(columns=[df.columns[0],df.columns[-1]],inplace=True)

In [3]:
req_cols=["ID","Preferred Foot","Weak Foot","Skill Moves","Work Rate",'Body Type', 'Real Face', 'Position', 'Height', 'Weight',
        'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling',
       'GKKicking', 'GKPositioning', 'GKReflexes']

In [4]:
temp_df=df[req_cols]
data=temp_df.values

categorical=[]
for i in range(data.shape[1]):
    if(type(data[0][i])==str):
        categorical.append(i)

ind=[]
for i in range(2):
    if(temp_df[req_cols[i]].isnull().values.any()):
        ind.extend(temp_df[temp_df[req_cols[i]].isnull()].index.to_list())

ind=list(set(ind))
temp_df=temp_df.drop(index=ind).reset_index()
temp_df

,index,ID,Preferred Foot,Weak Foot,Skill Moves,Work Rate,Body Type,Real Face,Position,Height,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
0,0,158023,Left,4.0,4.0,Medium/ Medium,Messi,Yes,RF,5'7,...,75.0,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0
1,1,20801,Right,4.0,5.0,High/ Low,C. Ronaldo,Yes,ST,6'2,...,85.0,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0
2,2,190871,Right,5.0,5.0,High/ Medium,Neymar,Yes,LW,5'9,...,81.0,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0
3,3,193080,Right,3.0,1.0,Medium/ Medium,Lean,Yes,GK,6'4,...,40.0,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0
4,4,192985,Right,5.0,4.0,High/ High,Normal,Yes,RCM,5'11,...,79.0,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18154,18202,238813,Right,2.0,2.0,Medium/ Medium,Lean,No,CM,5'9,...,43.0,45.0,40.0,48.0,47.0,10.0,13.0,7.0,8.0,9.0
18155,18203,243165,Right,2.0,2.0,Medium/ Medium,Normal,No,ST,6'3,...,43.0,42.0,22.0,15.0,19.0,10.0,9.0,9.0,5.0,12.0
18156,18204,241638,Right,3.0,2.0,Medium/ Medium,Normal,No,ST,5'8,...,55.0,41.0,32.0,13.0,11.0,6.0,5.0,10.0,6.0,13.0
18157,18205,246268,Right,3.0,2.0,Medium/ Medium,Lean,No,RW,5'10,...,50.0,46.0,20.0,25.0,27.0,14.0,6.0,14.0,8.0,9.0
18158,18206,246269,Right,3.0,2.0,Medium/ Medium,Lean,No,CM,5'10,...,33.0,43.0,40.0,43.0,50.0,10.0,15.0,9.0,12.0,9.0

In [30]:
prefixes=[]
for i in categorical:
    prefixes.append(req_cols[i])
    print(df[req_cols[i]].nunique(),req_cols[i])
    
df1=pd.get_dummies(temp_df,prefix=prefixes)
df1.set_index("index",inplace=True)
df1

30 Preferred Foot
13 Work Rate
17 Body Type
5 Real Face
28 Position
27 Height
67 Weight

,ID,Weak Foot,Skill Moves,HeadingAccuracy,ShortPassing,Volleys,Dribbling,Curve,FKAccuracy,LongPassing,...,Weight_5'10,Weight_5'11,Weight_5'6,Weight_5'7,Weight_5'9,Weight_6'0,Weight_6'1,Weight_6'2,Weight_6'3,Weight_6'4
index,,,,,,,,,,,,,,,,,,,,,
0,158023,4.0,4.0,70.0,90.0,86.0,97.0,93.0,94.0,87.0,...,0,0,0,0,0,0,0,0,0,0
1,20801,4.0,5.0,89.0,81.0,87.0,88.0,81.0,76.0,77.0,...,0,0,0,0,0,0,0,0,0,0
2,190871,5.0,5.0,62.0,84.0,84.0,96.0,88.0,87.0,78.0,...,0,0,0,0,0,0,0,0,0,0
3,193080,3.0,1.0,21.0,50.0,13.0,18.0,21.0,19.0,51.0,...,0,0,0,0,0,0,0,0,0,0
4,192985,5.0,4.0,55.0,92.0,82.0,86.0,85.0,83.0,91.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,2.0,2.0,40.0,49.0,25.0,42.0,30.0,34.0,45.0,...,0,0,0,0,0,0,0,0,0,0
18203,243165,2.0,2.0,52.0,43.0,36.0,39.0,32.0,20.0,25.0,...,0,0,0,0,0,0,0,0,0,0
18204,241638,3.0,2.0,46.0,38.0,38.0,45.0,38.0,27.0,28.0,...,0,0,0,0,0,0,0,0,0,0
18205,246268,3.0,2.0,39.0,42.0,40.0,51.0,34.0,32.0,32.0,...,0,0,0,0,0,0,0,0,0,0
18206,246269,3.0,2.0,46.0,48.0,30.0,43.0,40.0,34.0,44.0,...,0,0,0,0,0,0,0,0,0,0

In [58]:
data=df1.values
from sklearn.metrics import silhouette_score
class KMans:
    def __init__(self,num_clusters):
        self.num_clusters=num_clusters
    
    def fit(self,data):
        self.data=data
        ind=self.initialize_clusters()
        self.cluster_centres=self.data[ind]
        self.cluster_centres=self.cluster_centres[:,1:]
        self.cluster={i:[] for i in range(self.num_clusters)}
        self.compute_clusters()

    def initialize_clusters(self):
        init_clusters=np.random.choice(range(1,len(self.data)),self.num_clusters,replace=False)
        print(init_clusters)
        return init_clusters
    
    def dist(self,a,b):
        return sum((a-b)**2)

    def compute_clusters(self):
        iter=1
  
        while(iter<=50):
            prev=self.cluster
            self.cluster={i:[] for i in range(self.num_clusters)}
            dist_matrix=pd.DataFrame()
            for i in range(len(self.cluster_centres)):
              dist_matrix[i]=np.apply_along_axis(lambda x: self.dist(x[1:],self.cluster_centres[i]),1,self.data)
          
            
            dist_matrix=dist_matrix.values
            cls=np.argmin(dist_matrix,axis=1)
            for i in range(len(cls)):
              self.cluster[cls[i]].append(i)

            for i in range(self.num_clusters):
              print(len(prev[i]),len(self.cluster[i]))
            
            print("Iteration",iter)

            if(prev==self.cluster or iter>50):
                break
              
              

            self.recompute_cluster_centers()
            iter+=1

    
    def recompute_cluster_centers(self):
        for i in self.cluster:

            vals=self.data[self.cluster[i],1:]
            centroid=np.mean(vals,axis=0)
            self.cluster_centres[i]=centroid
    
    def predict(self,x):
      x=np.array(x)
      preds=pd.DataFrame()
      for i in range(len(self.cluster_centres)):
        preds[i]=np.apply_along_axis(lambda x: self.dist(x[1:],self.cluster_centres[i]),1,x)

      cls=np.argmin(preds,axis=1)
      return cls
      


        
  
from sklearn.cluster import KMeans
for i in range(3,10,1):
  clusterer=KMeans(n_clusters=i, random_state=10)
  cluster_labels = clusterer.fit_predict(data[:,1:])
  # clusterer.fit(data)
  print(i,"score :",silhouette_score(data[:,1:],cluster_labels))

3 score : 0.3082439684271908
4 score : 0.2907552639214484
5 score : 0.25878089945970173
6 score : 0.22312216137529114
7 score : 0.21931141352855124
8 score : 0.21064386772185886
9 score : 0.19846649093892688

5518719000000.0